#!/bin/bash
# Whonix build selection script 

clear
echo "=============================================================="
echo "What would you like to do?"
echo ""
echo "Build Whonix-Gateway virtual machine image	       —> Press 1 "
echo "Build Whonix-Workstation virtual machine image     —> Press 2 "
echo "Exit the build menu	                               —> Press 3 "
echo ""
echo "Choose one option and press Enter"
echo "=============================================================="
read n 
case $n in
     1)	~/Whonix/whonix_build —build —tor-gateway & echo "Building Whonix-Gateway virtual machine image";;
     2)	~/Whonix/whonix_build —build —tor-workstation & echo "Building Whonix-Workstation virtual machine image";; 
     3)	exit & echo "Exiting the build menu";;
     *) exit & echo "Exiting the build menu";;
esac
