#!/bin/bash
# Whonix build script

# apt-get update
# apt-get dist-upgrade -y

git clone https://github.com/adrelanos/Whonix &&
clear
git -C "/home/user/Whonix" checkout 7.7.3

echo "=============================================================="
echo "What would you like to do?"
echo ""
echo "Build Whonix-Gateway virtual machine image         --> Press 1 "
echo "Build Whonix-Workstation virtual machine image --> Press 2 "
echo "Build Whonix-Gateway on hardware        --> Press 3 "
echo "Exit the build menu         --> Press 0 "
echo ""
echo "Choose one option and press Enter"
echo "=============================================================="
read answer

case $answer in 1)
sudo ./Whonix/whonix_build --build --tor-gateway
esac

case $answer in 2)
sudo ./Whonix/whonix_build --build --tor-workstation
esac

case $answer in 3)
sudo ./Whonix/whonix_build --tor-gateway --bare-metal --build
esac

case $answer in 0)
exit & echo "Exiting the build menu"
esac
