#!/bin/bash

# Works if you are root but not as user

# No password required for sudo commands. This could be refined just for the whonix build command
echo "user ALL = NOPASSWD : ALL" >> /etc/sudoers

# Deletes the 54th line from /etc/innittab - 
sed -i '54d' /etc/inittab

# Adds the autologin command 
echo "1:2345:respawn:/bin/login -f user tty1 </dev/tty1 >/dev/tty1 2>&1" >> /etc/inittab

reboot
