#!/bin/bash
# Whonix build script
echo "=============================================================="
echo "What would you like to do?"
echo ""
echo "Build Whonix-Gateway virtual machine image	    --> Press 1 "
echo "Build Whonix-Workstation virtual machine image    --> Press 2 "
echo "Build Whonix-Gateway on hardware	--> Press 3 "
echo "Exit the build menu	                            --> Press 0 "
echo ""
echo "Choose one option and press Enter"
echo "=============================================================="
read answer

case $answer in 1)
sudo ./Whonix/whonix_build --build --tor-gateway & echo "Building Whonix-Gateway virtual machine image"
esac

case $answer in 2)
sudo ./Whonix/whonix_build --build --tor-workstation & echo "Building Whonix-Workstation virtual machine image"
esac

case $answer in 3)
sudo ./Whonix/whonix_build --tor-gateway --bare-metal --build & echo "Installing Whonix-Gateway on hardware"
esac

case $answer in 0)
exit & echo "Exiting the build menu"
esac
